//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CofileUI.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CofileUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All Encrypt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Dialog_AllEncrypt_Title {
            get {
                return ResourceManager.GetString("Dialog_AllEncrypt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap directory {
            get {
                object obj = ResourceManager.GetObject("directory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;type&quot;: &quot;file&quot;,
        ///  &quot;comm_option&quot;: {
        ///    &quot;sid&quot;: &quot;API&quot;,
        ///    &quot;item&quot;: &quot;AES256&quot;,
        ///    &quot;#encode_type&quot;: &quot;0: binary, 1: ASCII&quot;,
        ///    &quot;encode_type&quot;: &quot;0&quot;,
        ///    &quot;log_console_yn&quot;: false,
        ///    &quot;header_file_save_yn&quot;: false,
        ///    &quot;file_reserver_yn&quot;: true,
        ///    &quot;dir_monitoring_yn&quot;: false,
        ///    &quot;dir_monitoring_term&quot;: 1,
        ///    &quot;verify_yn&quot;: false,
        ///    &quot;schedule_time&quot;: &quot;12:00&quot;
        ///  },
        ///  &quot;enc_option&quot;: {
        ///    &quot;#input_filter&quot;: &quot;[.]txt$&quot;,
        ///    &quot;#output_suffix_head&quot;: &quot;head_&quot;,
        ///    &quot;#output_suffix_tail&quot;: &quot;_tail&quot;,
        ///    &quot;input_d[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string file_config_default {
            get {
                return ResourceManager.GetString("file_config_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;type&quot;: &quot;sam&quot;,
        ///  &quot;comm_option&quot;: {
        ///    &quot;#sam_type&quot;: &quot;0:var 1:fixed&quot;,
        ///    &quot;sam_type&quot;: 0,
        ///    &quot;no_col&quot;: 2,
        ///    &quot;sid&quot;: &quot;API&quot;,
        ///    &quot;delimiter&quot;: &quot;||&quot;,
        ///    &quot;trim&quot;: 0,
        ///    &quot;skip_header&quot;: 0,
        ///    &quot;record_len&quot;: 0,
        ///    &quot;#input_filter&quot;: &quot;[.]sam$&quot;,
        ///    &quot;input_dir&quot;: &quot;/&quot;,
        ///    &quot;input_ext&quot;: &quot;sam&quot;,
        ///    &quot;output_dir&quot;: &quot;/&quot;,
        ///    &quot;output_ext&quot;: &quot;enc&quot;,
        ///    &quot;dir_monitoring_yn&quot;: false,
        ///    &quot;dir_monitoring_term&quot;: 1,
        ///    &quot;#no_access_sentence&quot;: &quot;Encrypted&quot;,
        ///    &quot;#log_file&quot;: &quot;sam_debug.log&quot;
        ///  },
        ///  &quot;col_var&quot;: [
        ///  [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string sam_config_default {
            get {
                return ResourceManager.GetString("sam_config_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///  &quot;type&quot;: &quot;tail&quot;,
        ///  &quot;comm_option&quot;: {
        ///    &quot;input_dir&quot;: &quot;/&quot;,
        ///    &quot;input_ext&quot;: &quot;log&quot;,
        ///    &quot;output_dir&quot;: &quot;/&quot;,
        ///    &quot;output_ext&quot;: &quot;enc&quot;,
        ///    &quot;sid&quot;: &quot;API&quot;,
        ///    &quot;#tail_type&quot;: &quot;1:LINE, 2:PATTERN&quot;,
        ///    &quot;tail_type&quot;: 2,
        ///    &quot;interval&quot;: 1,
        ///    &quot;no_inform&quot;: 2,
        ///    &quot;#input_filter&quot;: &quot;log_([1-2][0-9]{3}_[0-1][0-9]_[0-3][0-9]).log$&quot;,
        ///    &quot;#input_filter_ex&quot;: &quot;log_2016_09_27.log&quot;,
        ///    &quot;#shutdown_time&quot;: 24,
        ///    &quot;zero_byte_yn&quot;: true
        ///  },
        ///  &quot;enc_inform&quot;: [
        ///    {
        ///      &quot;item&quot;: &quot;ARIA256CBC&quot;,
        ///      &quot;#pattern&quot;: [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tail_config_default {
            get {
                return ResourceManager.GetString("tail_config_default", resourceCulture);
            }
        }
    }
}
